number: null
at: 2020-02-01T02:26:30.748Z
by: Patrick Kettner
environment: local
commit:
  sha: eb0c54d29
  message: |-
    Properly extract strings for i18n on non documentation pages

    this ia part of hte ongoing i18n ramp up. this (should) go though
    everything that is not a part of documentation pages, and ensure that
    any user visible strings are going through the gettext i18n process
